// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID    int32
	Uuid      pgtype.UUID
	Name      string
	Email     string
	CreatedAt pgtype.Timestamptz
}
